nexus-material: END_STONE
nexus-health: 75
xp-message: "&a+12 Shotbow XP"
nexus-destruction-delay: 1
nexus-hit-delay: 20

# Grapple Ability Settings
grapple:
  pull-strength-multiplier: 0.15
  durability-loss-chance: 0.25
  hook-speed-multiplier: 1.0
  upward-pull-boost: 0.1
  hook-has-gravity: true
